// Purpose: Compare exact constrained decisions against an independent exhaustive oracle and hostile plugins.
import test from 'node:test';
import assert from 'node:assert/strict';
import { solve, solveWith, satisfies, validateProblem } from '../src/index.mjs';
const problem = () => ({ schemaVersion: 1, variables: ['a', 'b'].map(id => ({ id, options: [{ id: 'high', description: 'high utility', score: 10, resources: { energy: 2 } }, { id: 'low', description: 'low cost', score: 3, resources: { energy: 1 } }] })), constraints: [{ type: 'budget', resource: 'energy', limit: 3 }] });
test('maximize summed utilities while respecting global budget', () => { const result = solve(problem()); assert.equal(result.status, 'optimal'); assert.equal(result.utility, 13); assert.ok(satisfies(problem(), result.assignment)); assert.equal(result.execution, 'not_executed'); });
test('requires and forbidden combinations are enforced', () => { const p = problem(); p.constraints.push({ type: 'requires', when: { a: 'high' }, then: { b: 'high' } }, { type: 'forbid', assignments: { a: 'low', b: 'high' } }); assert.deepEqual(solve(p).assignment, { a: 'low', b: 'low' }); });
test('unsatisfiable and truncated searches have different statuses', () => { const p = problem(); p.constraints[0].limit = 0; assert.equal(solve(p).status, 'unsatisfiable'); assert.equal(solve(problem(), { maxStates: 1 }).status, 'incomplete'); assert.equal(solve(problem(), { maxStates: 1 }).complete, false); });
test('small randomized problems match independent exhaustive enumeration', () => { let seed = 7; const random = () => ((seed = (seed * 1664525 + 1013904223) >>> 0) % 20); for (let n = 0; n < 40; n++) { const p = problem(); p.constraints[0].limit = random() % 5; for (const v of p.variables) for (const o of v.options) o.score = random() - 10; const totals = []; for (const a of p.variables[0].options) for (const b of p.variables[1].options) if (a.resources.energy + b.resources.energy <= p.constraints[0].limit) totals.push(a.score + b.score); assert.equal(solve(p).utility, totals.length ? Math.max(...totals) : null); } });
test('reject unsafe ids, negative resource costs, unknown constraints', () => { const p = problem(); p.variables[0].id = '__proto__'; assert.throws(() => validateProblem(p)); const q = problem(); q.variables[0].options[0].resources.energy = -1; assert.throws(() => solve(q)); const r = problem(); r.constraints.push({ type: 'arbitrary_code' }); assert.throws(() => solve(r)); });
test('external backend must satisfy immutable original constraints', async () => { const p = problem(); await assert.rejects(solveWith(p, async copy => { copy.constraints = []; p.constraints = []; return { assignment: { a: 'high', b: 'high' } }; }), /invalid assignment/); const r = await solveWith(problem(), async () => ({ assignment: { a: 'low', b: 'high' }, status: 'optimal' })); assert.equal(r.optimalityVerified, false); });
test('backend deadlines and cancellation propagate', async () => { await assert.rejects(solveWith(problem(), () => new Promise(() => {}), { timeoutMs: 5 }), /deadline/); assert.throws(() => solve(problem(), { signal: AbortSignal.abort(new Error('cancelled')) }), /cancelled/); });
